# CircleCI configuration file that defines a pipeline.

version: 2.1

# Cammands that can be called as steps in any job(s) in this config
commands:
  say_hello_cmd:
    steps:
      - run: echo "Hello from commands.say_hello_cmd.steps[0]"
      - my_command_cmd
  my_command_cmd:
    steps:
      - run: echo "This is a command"

# Jobs are reponsible for running a series of _steps_ that performs command.
jobs:
  hello-job: # this is a job, it can run multiple steps.
    docker:
      - image: cimg/node:22.17
    steps:
      - checkout
      - run: echo "Hello from jobs.hello-job.steps[1]"
      - say_hello_cmd

workflows:
  my-workflow:
    jobs:
      - hello-job
  other_workflow:
    jobs:
      - my-job:
          docker:
            - image: cimg/node:22.17
          steps:
            - run: echo "hello from worflows.other_workflow.jobs[0].my-job.steps[0]"
