# CircleCI configuration file that defines a pipeline.
# https://circleci.com/docs/configuration-reference/

version: 2.1

# Cammands that can be called as steps in any job(s) in this config
commands:
  say_hello_cmd:
    steps:
      - run: echo "Hello world"
      - my_command_cmd
  my_command_cmd:
    steps:
      - run: echo "This is a command"

# Jobs are reponsible for running a series of _steps_ that performs command.
jobs:
  hello-job: # this is a job, it can run multiple steps.
    docker:
      - image: cimg/node:22.17
    steps:
      - checkout
      - run: echo "Hello from jobs.hello-job.steps[1]"
      - say_hello_cmd
  my-job:
    docker:
      - image: cimg/node:22.17
    steps:
      - run: echo "hello from my-job"
      - run: echo "Hello ${FOO}"

  job1:
    docker:
      - image: cimg/node:lts
    steps:
      - run: whoami; pwd; ls -la $HOME
      - run: mkdir -p /tmp/workspace
      - run: echo "bar" >> /tmp/workspace/foo.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - foo.txt

  job2:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -l /tmp/workspace

# Workflows are responsible for orchestrating multiple jobs.
# Define the run order, dependencies and approval.
workflows:
  my-workflow:
    jobs:
      - job1
      - job2

  # other-workflow:
  #   jobs:
  #     - my-job:
  #         context:
  #           - test-context
