# CircleCI configuration file that defines a pipeline.
# https://circleci.com/docs/configuration-reference/

version: 2.1

# Cammands that can be called as steps in any job(s) in this config
commands:
  say_hello_cmd:
    steps:
      - run: echo "Hello world"
      - my_command_cmd
  my_command_cmd:
    steps:
      - run: echo "This is a command"

# Jobs are reponsible for running a series of _steps_ that performs command.
jobs:
  hello-job: # this is a job, it can run multiple steps.
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: echo "Hello from jobs.hello-job.steps[1]"
      - say_hello_cmd
  my-job:
    docker:
      - image: cimg/node:lts
    steps:
      - run: echo "hello from my-job"
      - run: echo "Hello ${FOO}"

  job1:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: >
          echo "user: $(whoami)";
          echo "pwd: $(pwd)";
          echo -e "current dir:\n$(ls -la)"
      - run: >
          mkdir -p /tmp/workspace;
          echo $FOO >> /tmp/workspace/foo.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - foo.txt

  job2:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/foo.txt

# Workflows are responsible for orchestrating multiple jobs.
# Define the run order, dependencies and approval.
workflows:
  my-workflow:
    jobs:
      - job1:
          context:
            - test-context
      - job2:
          requires:
            - job1
