# CircleCI configuration file that defines a pipeline.
# https://circleci.com/docs/concepts/
# https://circleci.com/docs/configuration-reference/

version: 2.1

commands:
  print_user_cmd:
    steps:
      - run:
          name: print user
          command: 'echo "user: $(whoami)"'
  print_cwd_cmd:
    steps:
      - run:
          name: print current working directory
          command: 'echo "pwd: $(pwd)"'
  print_current_dir_cmd:
    steps:
      - run:
          name: print content of `cwd`
          command: 'echo -e "current dir:\n$(ls -la)"'
  print_info_cmd:
    steps:
      - print_user_cmd
      - print_cwd_cmd
      - print_current_dir_cmd

jobs:
  create_file:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - print_info_cmd
      - run:
          name: create file foo.txt
          command: >
            mkdir -p /tmp/workspace;
            echo "${FOO}" >> /tmp/workspace/foo.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - foo.txt
  read_file:
    docker:
      - image: cimg/base:current
    steps:
      - print_info_cmd
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: print content of foo.txt
          command: cat /tmp/workspace/foo.txt

  job1:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: test 3 with |
          command: |
            ls -l | \
            grep circleci

workflows:
  my-workflow:
    jobs:
      - job1
      # - create_file:
      #     context:
      #       - test-context
      # - read_file:
      #     requires:
      #       - create_file
